server:
  port: 9095


spring:
  jpa:
    properties:
      hibernate:
        dialect: com.example.cqrs.config.SnowflakeDialect
    hibernate:
      ddl-auto: none
  datasource:
    name: snowflake-pool-props
    driverClassName: net.snowflake.client.jdbc.SnowflakeDriver
    url: jdbc:snowflake://vn75069.australia-east.azure.snowflakecomputing.com/?warehouse=TEST_WH&db=TESTDB&schema=PUBLIC&CLIENT_RESULT_COLUMN_CASE_INSENSITIVE=true
    username: ishmahajan
    password: BoeingB17^
