server:
  port: 9090

spring.h2.console.enabled: true
spring.h2.console.path: /h2-console

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  rabbitmq:
    addresses: localhost:5672
    password: admin
    username: admin
    listener:
      simple:
        concurrency: 4
        max-concurrency: 8
        prefetch: 162
      concurrency: 4
      max-concurrency: 8
      prefetch: 162
  cloud:
    function:
      definition: buyer
    stream:
      bindings:
        vehicle-notification-channel:
          destination: vehicle-events
        buyer-in-0:
          destination: vehicle-events
          group: buyer
